Work on generics in ResourceState
icerockdev/moko-mvvm pull request #152
Opened 2021-07-10 10:27 UTC by y9san9

Generics now are more meaningful, and redundant generics were removed

2021-07-10 10:28 UTC, y9san9 commented
@Alex009 I did

2021-07-13 17:04 UTC, Alex009 requested changes

2021-07-13 17:04 UTC, Alex009 commented on mvvm-state/src/commonMain/kotlin/dev/icerock/moko/mvvm/StateExt.kt
> +    ResourceState.Empty
we should also add into release notes guide to migration. please add migration regexp to pr description, we will add it into release notes later

2021-07-13 17:04 UTC, Alex009 commented on mvvm-state/src/commonMain/kotlin/dev/icerock/moko/mvvm/ResourceState.kt
> +sealed class ResourceState<out TData, out TError> {
this change should support simple automatically migration if we want to merge it...try to write some regexp which will allow us and others migrate to new version in minutes on any size of project codebase

2026-06-01 02:11 UTC, Alex009 commented
Moved to separated lib https://github.com/icerockdev/moko-state

2026-06-01 02:11 UTC, closed without merging